CREATE TYPE "AppointmentType" AS ENUM ('BLOOD_DONATION', 'ELIGIBILITY_SCREENING', 'FOLLOW_UP', 'EMERGENCY_DONATION');

ALTER TABLE "Appointment" ADD COLUMN "appointmentType" "AppointmentType" NOT NULL DEFAULT 'BLOOD_DONATION';
