ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'DONOR_ARRIVED';
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';

ALTER TABLE "Appointment"
  ADD COLUMN IF NOT EXISTS "cancelledBy" TEXT;
