export default () => ({
  app: {
    port: parseInt(process.env.PORT ?? '4000', 10),
    env: process.env.NODE_ENV ?? 'development',
  },
  cors: {
    origins: (process.env.CORS_ORIGINS ?? 'http://localhost:5173').split(','),
  },
  jwt: {
    accessSecret: process.env.JWT_ACCESS_SECRET ?? 'replace-me',
    refreshSecret: process.env.JWT_REFRESH_SECRET ?? 'replace-me',
    accessTtl: process.env.JWT_ACCESS_TTL ?? '15m',
    refreshTtlDays: parseInt(process.env.JWT_REFRESH_TTL_DAYS ?? '7', 10),
  },
  security: {
    resetTokenTtlMinutes: parseInt(process.env.RESET_TOKEN_TTL_MINUTES ?? '30', 10),
    emailVerificationTtlMinutes: parseInt(process.env.AUTH_VERIFICATION_CODE_EXPIRY_MINUTES ?? process.env.EMAIL_VERIFICATION_TTL_MINUTES ?? '5', 10),
    verificationResendCooldownSeconds: parseInt(process.env.AUTH_VERIFICATION_RESEND_COOLDOWN_SECONDS ?? '45', 10),
    verificationMaxResendsPerHour: parseInt(process.env.AUTH_VERIFICATION_MAX_RESENDS_PER_HOUR ?? '5', 10),
    verificationMaxAttemptsPerCode: parseInt(process.env.AUTH_VERIFICATION_MAX_ATTEMPTS_PER_CODE ?? '5', 10),
  },
  smtp: {
    host: process.env.SMTP_HOST ?? '',
    port: parseInt(process.env.SMTP_PORT ?? '587', 10),
    user: process.env.SMTP_USER ?? '',
    pass: process.env.SMTP_PASS ?? '',
    from: process.env.SMTP_FROM ?? process.env.SMTP_USER ?? 'no-reply@bloodresponse.local',
  },
  sms: {
    enabled: process.env.SMS_ENABLED === 'true',
    provider: process.env.SMS_PROVIDER ?? 'console',
    from: process.env.SMS_FROM ?? 'BloodResponse',
    bmsEnabled: process.env.BMS_SMS_ENABLED === 'true',
    bmsApiKey: process.env.BMS_API_KEY ?? '',
    bmsBaseUrl: process.env.BMS_BASE_URL ?? 'https://api.mnotify.com/api',
    bmsSenderId: process.env.BMS_SENDER_ID ?? 'BloodSOS',
    bmsTimeoutMs: parseInt(process.env.BMS_SMS_TIMEOUT_MS ?? '15000', 10),
    bmsMaxRecipients: parseInt(process.env.BMS_SMS_MAX_RECIPIENTS ?? '100', 10),
    bmsRetryAttempts: parseInt(process.env.BMS_SMS_RETRY_ATTEMPTS ?? '2', 10),
    donorContactExportMaxRows: parseInt(process.env.DONOR_CONTACT_EXPORT_MAX_ROWS ?? '5000', 10),
    smsCampaignMaxRecipients: parseInt(process.env.SMS_CAMPAIGN_MAX_RECIPIENTS ?? '1000', 10),
    smsCampaignBatchSize: parseInt(process.env.SMS_CAMPAIGN_BATCH_SIZE ?? '100', 10),
    smsCampaignMessageMaxLength: parseInt(process.env.SMS_CAMPAIGN_MESSAGE_MAX_LENGTH ?? '480', 10),
    twilioAccountSid: process.env.TWILIO_ACCOUNT_SID ?? '',
    twilioAuthToken: process.env.TWILIO_AUTH_TOKEN ?? '',
    twilioFromNumber: process.env.TWILIO_FROM_NUMBER ?? '',
    africasTalkingUsername: process.env.AFRICAS_TALKING_USERNAME ?? '',
    africasTalkingApiKey: process.env.AFRICAS_TALKING_API_KEY ?? '',
  },
  donorSixMonthReminder: {
    enabled: process.env.DONOR_SIX_MONTH_REMINDER_ENABLED === 'true',
    cron: process.env.DONOR_SIX_MONTH_REMINDER_CRON ?? '0 8 * * *',
    timezone: process.env.DONOR_SIX_MONTH_REMINDER_TIMEZONE ?? 'Africa/Accra',
    months: parseInt(process.env.DONOR_SIX_MONTH_REMINDER_MONTHS ?? '6', 10),
  },
  ai: {
    enabled: process.env.AI_INTELLIGENCE_ENABLED !== 'false',
    demandLookbackDays: parseInt(process.env.AI_DEMAND_LOOKBACK_DAYS ?? '30', 10),
    expiryWarningDays: parseInt(process.env.AI_EXPIRY_WARNING_DAYS ?? '7', 10),
    defaultRadiusKm: parseInt(process.env.AI_DEFAULT_RADIUS_KM ?? '20', 10),
    defaultDonorLimit: parseInt(process.env.AI_DEFAULT_DONOR_LIMIT ?? '25', 10),
    highRiskScore: parseInt(process.env.AI_HIGH_RISK_SCORE ?? '70', 10),
    criticalRiskScore: parseInt(process.env.AI_CRITICAL_RISK_SCORE ?? '85', 10),
    minDonorRecommendationScore: parseInt(process.env.AI_MIN_DONOR_RECOMMENDATION_SCORE ?? '50', 10),
  },
  assistant: {
    enabled: process.env.ASSISTANT_ENABLED !== 'false',
    publicEnabled: process.env.ASSISTANT_PUBLIC_ENABLED !== 'false',
    contextTtlMinutes: parseInt(process.env.ASSISTANT_CONTEXT_TTL_MINUTES ?? '30', 10),
    maxMessageLength: parseInt(process.env.ASSISTANT_MAX_MESSAGE_LENGTH ?? '500', 10),
    publicRateLimit: parseInt(process.env.ASSISTANT_PUBLIC_RATE_LIMIT ?? '20', 10),
    authRateLimit: parseInt(process.env.ASSISTANT_AUTH_RATE_LIMIT ?? '60', 10),
  },
});
